### ISSUE TITLE
both "autoevent" and "scheduler" call "HandleReadCommands" which causes crash

### ISSUE THREAD

**Issue by nbfhscl** [edgexfoundry/device-mqtt-go#88] opened 2019-08-05 01:31 UTC
Using 1.0.1 images, I add one mock-mqtt device which sends data "randfloat64" every 5s, set up a "5s" autoevent of deviceresoure "ping", and one scheduler of "testmessage" occur every 3s, then I find the edgex-device-mqtt frequently disconnect and reconnect to the broker, after several minutes the service panics with following kinds of errors. 
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x46f039]
goroutine 4102 [running]:
io.ReadAtLeast(0x0, 0x0, 0xc0001930c0, 0x1, 0x1, 0x1, 0xa4dea0, 0xa54f01, 0xc0001930c0)
       /usr/local/go/src/io/io.go:310 +0x59
io.ReadFull(0x0, 0x0, 0xc0001930c0, 0x1, 0x1, 0x1, 0x0, 0xc000562de8)
       /usr/local/go/src/io/io.go:329 +0x58
github.com/eclipse/paho.mqtt.golang/packets.ReadPacket(0x0, 0x0, 0x0, 0x0, 0x0, 0xa90300)
       /go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.1.1/packets/packets.go:105 +0x9f
github.com/eclipse/paho%2emqtt%2egolang.(*client).connect(0xc000631c00, 0xc414e0)
       /go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.1.1/client.go:399 +0xe9
github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1(0xc000631c00, 0xc0001140b0, 0xc0005bdb80)
       /go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.1.1/client.go:223 +0x3c9
created by github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect
       /go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.1.1/client.go:195 +0x1eb
```
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8b24de]
goroutine 589 [running]:
github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost(0xc0003e5c00, 0xc41480, 0xc0000baa00)
       /go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.1.1/client.go:460 +0x5e
created by github.com/eclipse/paho%2emqtt%2egolang.errorWatch
       /go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.1.1/net.go:332 +0x1df
```
the reason may be as stated in the title. both "autoevent" and "scheduler" call "HandleReadCommands" and register to mqtt broker using the same "clientID" get from "connectionInfo.ClientId", conflict arises and for some reason the service panics.
when I leave the "ClientId" in protocol to be blank, it works all fine.

**Comment by lenny-intel** [comment] 2019-08-05 15:50
Sounds like a race condition similar to the one we had with subscribing to ZMQ. Best guess is the `paho.mqtt` package is not thread safe. May need to put a mutex around the `register to mqtt broker`

**Comment by weichou1229** [comment] 2019-08-08 05:27
I reproduce the error by create three autoEvents.
```
[[DeviceList]]
  Name = "MQ_DEVICE"
  Profile = "Test.Device.MQTT.Profile"
  Description = "General MQTT device"
  Labels = [ "MQTT"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
       Schema = "tcp"
       Host = "192.168.0.2"
       Port = "1883"
       ClientId = "CommandPublisher"
       User = ""
       Password = ""
       Topic = "CommandTopic"
  [[DeviceList.AutoEvents]]
    Frequency = "1s"
    OnChange = false
    Resource = "testrandnum"
  [[DeviceList.AutoEvents]]
    Frequency = "1s"
    OnChange = false
    Resource = "testping"
  [[DeviceList.AutoEvents]]
    Frequency = "1s"
    OnChange = false
    Resource = "testmessage"
```

```
level=DEBUG ts=2019-08-08T05:15:49.488789Z app=edgex-device-mqtt source=executor.go:42 msg="AutoEvent - executing {\"frequency\":\"1s\",\"resource\":\"testmessage\"}"
level=DEBUG ts=2019-08-08T05:15:49.488799Z app=edgex-device-mqtt source=executor.go:42 msg="AutoEvent - executing {\"frequency\":\"1s\",\"resource\":\"testping\"}"
level=DEBUG ts=2019-08-08T05:15:49.488799Z app=edgex-device-mqtt source=executor.go:42 msg="AutoEvent - executing {\"frequency\":\"1s\",\"resource\":\"testrandnum\"}"
level=DEBUG ts=2019-08-08T05:15:49.490254Z app=edgex-device-mqtt source=command.go:200 msg="Handler - execReadCmd: deviceResource: message"
level=DEBUG ts=2019-08-08T05:15:49.490644Z app=edgex-device-mqtt source=command.go:200 msg="Handler - execReadCmd: deviceResource: ping"
level=DEBUG ts=2019-08-08T05:15:49.49095Z app=edgex-device-mqtt source=command.go:200 msg="Handler - execReadCmd: deviceResource: randnum"
level=DEBUG ts=2019-08-08T05:15:49.491524Z app=edgex-device-mqtt source=command.go:207 msg="Handler - execReadCmd: deviceResource: {\"description\":\"device message\",\"name\":\"message\",\"properties\":{\"value\":{\"type\":\"String\",\"readWrite\":\"W\",\"size\":\"0\"},\"units\":{\"type\":\"String\",\"readWrite\":\"R\"}}}"
level=DEBUG ts=2019-08-08T05:15:49.491582Z app=edgex-device-mqtt source=command.go:207 msg="Handler - execReadCmd: deviceResource: {\"description\":\"device awake\",\"name\":\"ping\",\"properties\":{\"value\":{\"type\":\"String\",\"readWrite\":\"R\",\"defaultValue\":\"pong\",\"size\":\"0\"},\"units\":{\"type\":\"String\",\"readWrite\":\"R\"}}}"
level=DEBUG ts=2019-08-08T05:15:49.491932Z app=edgex-device-mqtt source=command.go:207 msg="Handler - execReadCmd: deviceResource: {\"description\":\"device random number\",\"name\":\"randnum\",\"properties\":{\"value\":{\"type\":\"Float64\",\"readWrite\":\"R\",\"size\":\"4\",\"floatEncoding\":\"eNotation\"},\"units\":{\"type\":\"String\",\"readWrite\":\"R\"}}}"
level=INFO ts=2019-08-08T05:15:49.492125Z app=edgex-device-mqtt source=driver.go:279 msg="Create MQTT client and connection: uri=tcp://:@192.168.0.2:1883 clientID=CommandPublisher "
level=INFO ts=2019-08-08T05:15:49.492481Z app=edgex-device-mqtt source=driver.go:279 msg="Create MQTT client and connection: uri=tcp://:@192.168.0.2:1883 clientID=CommandPublisher "
level=INFO ts=2019-08-08T05:15:49.492816Z app=edgex-device-mqtt source=driver.go:279 msg="Create MQTT client and connection: uri=tcp://:@192.168.0.2:1883 clientID=CommandPublisher "
level=INFO ts=2019-08-08T05:15:49.496887Z app=edgex-device-mqtt source=driver.go:154 msg="Publish command: {\"cmd\":\"message\",\"method\":\"get\",\"uuid\":\"5d4bb0051da32727627da749\"}"
level=WARN ts=2019-08-08T05:15:49.497086Z app=edgex-device-mqtt source=driver.go:288 msg="Connection lost : EOF"
level=INFO ts=2019-08-08T05:15:49.497474Z app=edgex-device-mqtt source=driver.go:154 msg="Publish command: {\"cmd\":\"ping\",\"method\":\"get\",\"uuid\":\"5d4bb0051da32727627da74a\"}"
level=INFO ts=2019-08-08T05:15:49.497587Z app=edgex-device-mqtt source=driver.go:154 msg="Publish command: {\"cmd\":\"randnum\",\"method\":\"get\",\"uuid\":\"5d4bb0051da32727627da74b\"}"
level=WARN ts=2019-08-08T05:15:49.497988Z app=edgex-device-mqtt source=driver.go:288 msg="Connection lost : EOF"
level=WARN ts=2019-08-08T05:15:49.501355Z app=edgex-device-mqtt source=driver.go:291 msg="Reconnection failed : Network Error : %!s(<nil>)"
level=WARN ts=2019-08-08T05:15:49.501406Z app=edgex-device-mqtt source=driver.go:288 msg="Connection lost : write tcp 192.168.0.2:63071->192.168.0.2:1883: use of closed network connection"
level=WARN ts=2019-08-08T05:15:49.501584Z app=edgex-device-mqtt source=driver.go:288 msg="Connection lost : EOF"
level=WARN ts=2019-08-08T05:15:49.502569Z app=edgex-device-mqtt source=driver.go:288 msg="Connection lost : write tcp 192.168.0.2:63072->192.168.0.2:1883: use of closed network connection"
level=WARN ts=2019-08-08T05:15:49.502527Z app=edgex-device-mqtt source=driver.go:291 msg="Reconnection failed : Network Error : %!s(<nil>)"
```

**Comment by weichou1229** [comment] 2019-08-08 06:14
@nbfhscl @lenny-intel 
I think there are two way to solve this issue.

1.Put mutex to lock the request, this will take some latency.

2.Remove the clientID or leave the clientID empty and then Broker will provide unique clientID.

http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718031
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901059
> A Server MAY allow a Client to supply a ClientID that has a length of zero bytes, however if it does so the Server MUST treat this as a special case and assign a unique ClientID to that Client 

https://mosquitto.org/man/mosquitto-conf-5.html
> MQTT 3.1.1 allows clients to connect with a zero length client id and have the broker generate a client id for them. Use this option to allow/disallow this behaviour. Defaults to true.

What do you think?

**Comment by nbfhscl** [comment] 2019-08-09 07:43
@weichou1229 
Mock device has same issue too, when using more than one autoevents, func "onCommandReceivedFromBroker" was called by several goroutines and func "sendTestData" create mqtt client with same id "ResponsePublisher", which could causes failure.
```bash
INFO   2019-08-09 14:49:27   Handle read commands failed: can not fetch command response: method=get cmd=message
ERROR   2019-08-09 14:49:27   AutoEvent - error occurs when reading resource message
```
what about maintain several long-connected clients on demands

**Comment by weichou1229** [comment] 2019-08-09 08:10
Right! Alternative, You can create mock device according this [doc](https://docs.edgexfoundry.org/Ch-ExamplesAddingMQTTDevice.html#run-an-mqtt-device-simulator).
[Async value](https://docs.edgexfoundry.org/Ch-ExamplesAddingMQTTDevice.html#async-device-reading) is a long-connected connection to subscribe the readings. Maybe you can use async value instead of the scheduler job.

**Comment by kaponz** [comment] 2019-10-07 09:22
Hello,

I am triying to launch the command in order to find the executable command. However, i am stuck because of this error:

MQTT Docker log:
edgex-device-mqtt | level=INFO ts=2019-10-02T11:46:06.945546211Z app=edgex-device-mqtt source=driver.go:279 msg="Create MQTT client and connection: uri=tcp://:@172.19.0.1:1883 clientID=CommandPublisher "
edgex-device-mqtt | level=INFO ts=2019-10-02T11:46:06.947118137Z app=edgex-device-mqtt source=driver.go:154 msg="Publish command: {"cmd":"randnum","method":"get","uuid":"5d948dfeb8dd790001bf0c4e"}"
edgex-device-mqtt | level=INFO ts=2019-10-02T11:46:11.948379424Z app=edgex-device-mqtt source=driver.go:122 msg="Handle read commands failed: can not fetch command response: method=get cmd=randnum"
edgex-device-mqtt | level=ERROR ts=2019-10-02T11:46:11.948980258Z app=edgex-device-mqtt source=executor.go:45 msg="AutoEvent - error occurs when reading resource testrandnum"

We deleted the clientID and the autoevent, but we have this error.
Thank you

**Comment by cloudxxx8** [comment] 2019-10-25 09:21
make sure the sdk version in go.mod is later than 
github.com/edgexfoundry/device-sdk-go v0.0.0-20191023171807-49a95f741ef7

**Comment by weichou1229** [comment] 2019-12-10 02:26
@nbfhscl Do you still got this error?  Is it fine to close this issue?

**Comment by weichou1229** [comment] 2020-01-21 05:59
Close for no activity.

**Closed by weichou1229** 2020-01-21 05:59 UTC
